services:
  - type: web
    name: allied-erp-mvp
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
        value: .onrender.com
